[etc.files]
"host/hostname" = { target = "/etc/hostname", type = "template", owner = "root" }
"host/hosts" = { target = "/etc/hosts", type = "template", owner = "root" }
"locale/locale.gen" = { target = "/etc/locale.gen", type = "template", owner = "root" }
"locale/locale.conf" = { target = "/etc/locale.conf", type = "template",  owner = "root" }
"mkinitcpio.conf.d" = { target = "/etc/mkinitcpio.conf.d", type = "template", owner = "root" }
"tty1-autologin.conf" = { target = "/etc/systemd/system/getty@tty1.service.d/override.conf", type = "template", owner = "root" }

[user.files]
"environment.d" = "~/.config/environment.d"
"nanorc" = "~/.config/nano/nanorc"
"backgrounds" = { target = "~/.local/share/backgrounds", type = "symbolic" }

[pacman.files]
"pacman/pacman.conf" = { target = "/etc/pacman.conf", type = "template", owner = "root" }
"pacman/hooks" = { target = "/etc/pacman.d/hooks", type = "template", owner = "root" }

[paru.files]
"paru.conf" = { target = "/etc/paru.conf", type = "template", owner = "root" }

[bash.files]
"bash/bashrc" = "~/.bashrc"
"bash/bash_profile" = "~/.bash_profile"

[bin.files]
"bin" = "~/.local/bin"

[git.files]
"gitconfig" = "~/.gitconfig"

[xdg-user-dirs.files]
"xdg-user-dirs" = "~/.config"

[sway.files]
"sway" = "~/.config/sway"

[foot.files]
"foot.ini" = "~/.config/foot/foot.ini"

[waybar.files]
"waybar" = "~/.config/waybar"

[wlogout.files]
"wlogout/layout" = "~/.config/wlogout/layout"
"wlogout/style.css" = "~/.config/wlogout/style.css"
"wlogout/icons" = { target = "~/.local/share/wlogout/icons", type = "symbolic" }

[wofi.files]
"wofi" = "~/.config/wofi"

[mako.files]
"mako" = "~/.config/mako/config"

[sway]
depends = [
    "foot",
    "bin",
    "bash",
    "mako",
    "waybar",
    "wlogout",
    "wofi",
    "xdg-user-dirs",
    ]

[archlinux]
depends = ["etc", "user", "pacman", "paru", "sway"]
