[common.files]
# Local variables: hostname, ifname, user
"host/hostname" = { target = "/etc/hostname", type = "template", owner = "root" }
"host/hosts" = { target = "/etc/hosts", type = "template", owner = "root" }
"locale/locale.gen" = { target = "/etc/locale.gen", type = "template", owner = "root" }
"locale/locale.conf" = { target = "/etc/locale.conf", type = "template",  owner = "root" }
"environment" = { target = "/etc/environment", type = "template", owner = "root" }
"mkinitcpio.conf" = { target = "/etc/mkinitcpio.conf", type = "template", owner = "root" }
"nanorc" = { target = "/etc/nanorc", type = "template", owner = "root" }
"network" = { target = "/etc/systemd/network/20-wired.network", type = "template", owner = "root" }
"tty1-autologin.conf" = { target = "/etc/systemd/system/getty@tty1.service.d/override.conf", type = "template", owner = "root" }

[common.variables]
# The first locale is the default locale
locales = ["en_US"]
editor = "nano"

[pacman.files]
"pacman/pacman.conf" = { target = "/etc/pacman.conf", type = "template", owner = "root" }
"pacman/hooks" = { target = "/etc/pacman.d/hooks", type = "template", owner = "root" }

[paru.files]
"paru.conf" = { target = "/etc/paru.conf", type = "template", owner = "root" }

[bash.files]
"bash/bashrc" = "~/.bashrc"
"bash/bash_profile" = "~/.bash_profile"

[bin.files]
"bin" = "~/.local/bin"

[git.files]
# Local variables: git_email, git_name
"gitconfig" = "~/.gitconfig"

[xdg-user-dirs.files]
"xdg-user-dirs" = "~/.config"

[sway.files]
# Local variables: background_file
"sway" = "~/.config/sway/config"

[foot.files]
"foot.ini" = "~/.config/foot/foot.ini"

[waybar.files]
"waybar" = "~/.config/waybar"

[wlogout.files]
"wlogout/layout" = "~/.config/wlogout/layout"
"wlogout/style.css" = "~/.config/wlogout/style.css"
"wlogout/icons" = { target = "~/.local/share/wlogout/icons", type = "symbolic" }

[wofi.files]
"wofi" = "~/.config/wofi"

[mako.files]
"mako" = "~/.config/mako/config"

[sway]
depends = [
    "foot",
    "bin",
    "bash",
    "mako",
    "waybar",
    "wlogout",
    "wofi",
    "xdg-user-dirs",
    ]

[archlinux]
depends = ["common", "pacman", "paru", "sway"]
