#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# Command not found
if [ -f /usr/share/doc/pkgfile/command-not-found.bash ]; then
    . /usr/share/doc/pkgfile/command-not-found.bash
fi

{{#if (is_executable "cargo") ~}}
export PATH="$PATH:~/.local/bin:~/.cargo/bin"
{{else}}
export PATH="$PATH:~/.local/bin"
{{/if ~}}
