#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

# Command not found
if [ -f /usr/share/doc/pkgfile/command-not-found.bash ]; then
    . /usr/share/doc/pkgfile/command-not-found.bash
fi

export PATH="$PATH:/home/sergey/.local/bin:/home/sergey/.cargo/bin"
export EDITOR=helix
